[env]
# tell mise to do "corepack enable" after installing any Node version that supports corepack
MISE_NODE_COREPACK = 1

[tools]
node = "18"
python = "system"

[settings]
idiomatic_version_file_enable_tools = ["node", "java"]
